name: Code Quality Check

on:
  push:
    paths:
      - 'HeatController/**'
    branches:
      - main
  pull_request:
    paths:
      - 'HeatController/**'
    branches:
      - main

jobs:
  lint:
    name: Lint C++ Code
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy clang-format cppcheck

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 HeatController/

    - name: Run Clang-Tidy
      run: |
        clang-tidy HeatController/**/*.cpp -- -std=c++17

    - name: Format Check with Clang-Format
      run: |
        clang-format -i HeatController/**/*.cpp
        git diff --exit-code # Fail if formatting is not applied
