name: Increment Version

on:
  push:
    branches:
      - main
    paths:
      - 'HeatController/**'
      - '!HeatController/version.txt'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get current version
        id: version
        run: |
          VERSION=$(cat HeatController/version.txt)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Increment version
        run: |
          IFS='.' read -ra ADDR <<< "${{ env.VERSION }}"
          ((ADDR[2]++))
          NEW_VERSION="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
          echo $NEW_VERSION > HeatController/version.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add HeatController/version.txt
          git commit -m "Increment version to ${{ env.NEW_VERSION }}"
          git push
          
      - name: Create Tag
        run: |
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
