name: Increment Version

on:
  push:
    branches:
      - main
    paths:
      - 'HeatController/**'
      - '!HeatController/version.txt'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increment version
        id: increment_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch  # Inkrementiere die PATCH-Version
          tag_prefix: ''       # Kein Präfix vor der Version (z.B., kein "v")

      - name: Update version file
        run: |
          # Schreibe die neue Version in version.txt
          echo "${{ steps.increment_version.outputs.new_tag }}" > HeatController/version.txt

      - name: Commit updated version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add HeatController/version.txt
          git commit -m "Update version to ${{ steps.increment_version.outputs.new_tag }}"
          git push origin main
