name: Update README Version

on:
  push:
    paths:
      - 'HeatController/version.txt'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Read version
        id: version
        run: echo "VERSION=$(cat HeatController/version.txt)" >> $GITHUB_ENV
        
      - name: Update README
        run: |
          sed -i "s/Version: .*/Version: ${{ env.VERSION }}/" README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update version in README" || exit 0
          git push 