name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Lesen der aktuellen Version und Inkrementieren
      - name: Update version.txt
        id: update-version
        run: |
          VERSION_FILE="HeatController/version.txt"
          if [[ ! -f "$VERSION_FILE" ]]; then
            echo "Error: $VERSION_FILE not found!"
            exit 1
          fi

          # Aktuelle Version auslesen
          VERSION=$(cat "$VERSION_FILE")
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"

          # Patch-Version erhöhen
          PATCH=$((VERSION_PARTS[2] + 1))

          # Neue Version erstellen
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
          echo "$NEW_VERSION" > "$VERSION_FILE"

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # Änderungen committen und pushen
      - name: Commit and push updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add HeatController/version.txt
          git commit -m "Incremented version to ${{ env.new_version }}"
          git push
