name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read and increment version
        id: read_version
        run: |
          # Prüfen, ob die Datei existiert, andernfalls Version auf 0.1 setzen
          if [ -f "[GIT ROOT]/HeatController/version.txt" ]; then
            current_version=$(cat [GIT ROOT]/HeatController/version.txt)
            echo "Current version is $current_version"
          else
            current_version="0.1"
            echo "No version file found. Starting at 0.1."
          fi

          # Inkrementieren der Minor-Version
          major=$(echo "$current_version" | cut -d '.' -f 1)
          minor=$(echo "$current_version" | cut -d '.' -f 2)
     
