name: Increment Version

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger on, update if needed

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment version number
        run: |
          VERSION_FILE="HeatController/version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1" > "$VERSION_FILE"
          else
            VERSION=$(cat "$VERSION_FILE")
            VERSION=$((VERSION + 1))
            echo "$VERSION" > "$VERSION_FILE"
          fi

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "Increment version to $(cat HeatController/version.txt)"
