name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read current version
        id: read_version
        run: |
          if [ -f "[GIT ROOT]/HeatController/version.txt" ]; then
            current_version=$(cat [GIT ROOT]/HeatController/version.txt)
            echo "Current version is $current_version"
          else
            current_version=0
            echo "No version file found. Starting at 0."
          fi
          new_version=$((current_version + 1))
          echo "New version is $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update version file
        run: |
          echo "${{ env.new_version }}" > [GIT ROOT]/HeatController/version.txt

      - name: Commit updated version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add [GIT ROOT]/HeatController/version.txt
          git commit -m "Increment version to ${{ env.new_version }}"
        continue-on-error: true

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/n3roGit/HeatControl.git main
