name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment version number
        run: |
          VERSION_FILE="HeatController/version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1" > "$VERSION_FILE"
          else
            VERSION=$(cat "$VERSION_FILE")
            VERSION=$((VERSION + 1))
            echo "$VERSION" > "$VERSION_FILE"
          fi
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check git status to confirm changes
          git status
          
          # Stage and commit the version file update
          git add HeatController/version.txt
          git commit -m "Increment version to $(cat HeatController/version.txt)"
          
          # Push changes to the main branch with token authentication
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
