name: Increment Version

on:
  push:
    branches:
      - main  # Specify the branch to trigger the version increment on

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Increment version
        id: version_increment
        uses: phips28/gh-action-bump-version@v9.0.0
        with:
          path: 'HeatController/version.txt'  # Set the path to version.txt
          tag-prefix: ''  # Optional: Set a tag prefix, if needed
          skip-tag: true  # Skips tagging to avoid creating a Git tag with each increment

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add HeatController/version.txt
          git commit -m "Increment version to $(cat HeatController/version.txt)"
          git push
